substitutions:
  devicename: painel-01
  friendly_name: Painel-01
  switch1: Estoque 2
  switch2: Caixa
  switch3: Estoque 1
  switch4: Garagem
  switch5: Frente Escritorio
  switch6: Atendimento 1
  switch7: Entrada Garagem
  switch8: Atendimento 2
  switch9: Escritório 2
  switch10: Escritório 3
  switch11: Estoque 3
  switch12: Banheiro
  switch13: Sala Arquivo
  switch14: Cozinha
  switch15: Sala Rosmar
  switch16: Escritorio 1


###### CONFIG ######
  delay: 0ms
  
esphome:
  name: $devicename
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid_ci
  password: !secret wifi_password_ci
  fast_connect: true
  ap:
    ssid: $devicename
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

logger:
  baud_rate: 0
  level: debug

      
api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
i2c:
  sda: 21
  scl: 22
  scan: true
  frequency: 50 khz

mcp23017:
  - id: 'hub_relay1'
    address: 0x20

  - id: 'hub_switch1'
    address: 0x21

  - id: 'hub_switch2'
    address: 0x22

switch:
  - platform: restart
    name: ${friendly_name} Restart

###################################### OUTPUTS ######################################
output:
### relay 1 ###
  - platform: gpio
    id: relay_1
    pin:
      mcp23xxx: hub_relay1
      number: 6
      mode: OUTPUT
      inverted: true
### relay 2 ###
  - platform: gpio
    id: relay_2
    pin:
      mcp23xxx: hub_relay1
      number: 7
      mode: OUTPUT
      inverted: true
### relay 3 ###
  - platform: gpio
    id: relay_3
    pin:
      mcp23xxx: hub_relay1
      number: 4
      mode: OUTPUT
      inverted: true
### relay 4 ###
  - platform: gpio
    id: relay_4
    pin:
      mcp23xxx: hub_relay1
      number: 5
      mode: OUTPUT
      inverted: true
### relay 5 ###
  - platform: gpio
    id: relay_5
    pin:
      mcp23xxx: hub_relay1
      number: 2
      mode: OUTPUT
      inverted: true
### relay 6 ###
  - platform: gpio
    id: relay_6
    pin:
      mcp23xxx: hub_relay1
      number: 3
      mode: OUTPUT
      inverted: true
### relay 7 ###
  - platform: gpio
    id: relay_7
    pin:
      mcp23xxx: hub_relay1
      number: 0
      mode: OUTPUT
      inverted: true
### relay 8 ###
  - platform: gpio
    id: relay_8
    pin:
      mcp23xxx: hub_relay1
      number: 1
      mode: OUTPUT
      inverted: true
### relay 9 ###
  - platform: gpio
    id: relay_9
    pin:
      mcp23xxx: hub_relay1
      number: 9
      mode: OUTPUT
      inverted: true
### relay 10 ###
  - platform: gpio
    id: relay_10
    pin:
      mcp23xxx: hub_relay1
      number: 8
      mode: OUTPUT
      inverted: true

### relay 11 ###
  - platform: gpio
    id: relay_11
    pin:
      mcp23xxx: hub_relay1
      number: 11
      mode: OUTPUT
      inverted: true
### relay 12 ###
  - platform: gpio
    id: relay_12
    pin:
      mcp23xxx: hub_relay1
      number: 10
      mode: OUTPUT
      inverted: true
### relay 13 ###
  - platform: gpio
    id: relay_13
    pin:
      mcp23xxx: hub_relay1
      number: 12
      mode: OUTPUT
      inverted: true
### relay 14 ###
  - platform: gpio
    id: relay_14
    pin:
      mcp23xxx: hub_relay1
      number: 13
      mode: OUTPUT
      inverted: true
### relay 15 ###
  - platform: gpio
    id: relay_15
    pin:
      mcp23xxx: hub_relay1
      number: 15
      mode: OUTPUT
      inverted: true
### relay 16 ###
  - platform: gpio
    id: relay_16
    pin:
      mcp23xxx: hub_relay1
      number: 14
      mode: OUTPUT
      inverted: true

###################################### LIGHT ######################################
light:
### light relay 1 ###
  - platform: binary
    id: light_1
    name: $switch1
    output: relay_1
    restore_mode: always_off
### light relay 2 ###
  - platform: binary
    id: light_2
    name: $switch2
    output: relay_2
    restore_mode: always_off
### light relay 3 ###
  - platform: binary
    id: light_3
    name: $switch3
    output: relay_3
    restore_mode: always_off
### light relay 4 ###
  - platform: binary
    id: light_4
    name: $switch4
    output: relay_4
    restore_mode: always_off
### light relay 5 ###
  - platform: binary
    id: light_5
    name: $switch5
    output: relay_5
    restore_mode: always_off
### light relay 6 ###
  - platform: binary
    id: light_6
    name: $switch6
    output: relay_6
    restore_mode: always_off
### light relay 7 ###
  - platform: binary
    id: light_7
    name: $switch7
    output: relay_7
    restore_mode: always_off
### light relay 8 ###
  - platform: binary
    id: light_8
    name: $switch8
    output: relay_8
    restore_mode: always_off
### light relay 9 ###
  - platform: binary
    id: light_9
    name: $switch9
    output: relay_9
    restore_mode: always_off
### light relay 10 ###
  - platform: binary
    id: light_10
    name: $switch10
    output: relay_10
    restore_mode: always_off
### light relay 11 ###
  - platform: binary
    id: light_11
    name: $switch11
    output: relay_11
    restore_mode: always_off
### light relay 12 ###
  - platform: binary
    id: light_12
    name: $switch12
    output: relay_12
    restore_mode: always_off
### light relay 13 ###
  - platform: binary
    id: light_13
    name: $switch13
    output: relay_13
    restore_mode: always_off
### light relay 14 ###
  - platform: binary
    id: light_14
    name: $switch14
    output: relay_14
    restore_mode: always_off
### light relay 15 ###
  - platform: binary
    id: light_15
    name: $switch15
    output: relay_15
    restore_mode: always_off
### light relay 16 ###
  - platform: binary
    id: light_16
    name: $switch16
    output: relay_16
    restore_mode: always_off
    
###################################### ACIONAMENTO TECLAS FISICAS ######################################
binary_sensor:
  - platform: status
    name: ${friendly_name} Status

### Tecla switch relay 1 ###
  - platform: gpio
    name: sw1-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 7
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_4
    on_release:
      then:
        - light.toggle: light_4
        
### Tecla switch relay 2 ###
  - platform: gpio
    name: sw2-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 6
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_7
    on_release:
      then:
        - light.toggle: light_7 
        
### Tecla switch relay 3 ###
  - platform: gpio
    name: sw3-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 5
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_5 
    on_release:
      then:
        - light.toggle: light_5
        
### Tecla switch relay 4 ###
  - platform: gpio
    name: sw4-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 4
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_12
    on_release:
      then:
        - light.toggle: light_12
        
### Tecla switch relay 5 ###
  - platform: gpio
    name: sw5-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 3
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_6
    on_release:
      then:
        - light.toggle: light_6
        
### Tecla switch relay 6 ###
  - platform: gpio
    name: sw6-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 2
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_7
    on_release:
      then:
        - light.toggle: light_7
        
### Tecla switch relay 7 ###
  - platform: gpio
    name: sw7-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 1
      mode:
        input: true
        pullup: true
      inverted: false
#    on_press:
#      then:
#        - light.toggle: light_4
#    on_release:
#      then:
#        - light.toggle: light_4
        
### Tecla switch relay 8 ###
  - platform: gpio
    name: sw8-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 0
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_4 
    on_release:
      then:
        - light.toggle: light_4
        
### Tecla switch relay 9 ###
  - platform: gpio
    name: sw9-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 15
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_11
    on_release:
      then:
        - light.toggle: light_11
        
### Tecla switch relay 10 ###
  - platform: gpio
    name: sw10-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 14
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_16
    on_release:
      then:
        - light.toggle: light_16
        
### Tecla switch relay 11 ###
  - platform: gpio
    name: sw11-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 13
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_9
    on_release:
      then:
        - light.toggle: light_9
        
### Tecla switch relay 12 ###
  - platform: gpio
    name: sw12-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 12
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_10
    on_release:
      then:
        - light.toggle: light_10
        
### Tecla switch relay 13 ###
  - platform: gpio
    name: sw13-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 11
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_14
    on_release:
      then:
        - light.toggle: light_14
        
### Tecla switch relay 14 ###
  - platform: gpio
    name: sw14-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 10
      mode:
        input: true
        pullup: true
      inverted: false
#    on_press:
#      then:
#        - light.toggle: light_6
#        - light.toggle: light_8        
#    on_release:
#      then:
#        - light.toggle: light_6
#        - light.toggle: light_8
        
### Tecla switch relay 15 ###
  - platform: gpio
    name: sw15-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 9
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_1
    on_release:
      then:
        - light.toggle: light_1
           
### Tecla switch relay 16 ###
  - platform: gpio
    name: sw16-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch1
      number: 8
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_3
    on_release:
      then:
        - light.toggle: light_3
        
### Tecla switch relay 17 ###
  - platform: gpio
    name: sw17-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 7
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_16
    on_release:
      then:
        - light.toggle: light_16
        
### Tecla switch relay 18 ###
  - platform: gpio
    name: sw18-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 6
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_9
    on_release:
      then:
        - light.toggle: light_9
        
### Tecla switch relay 19 ###
  - platform: gpio
    name: sw19-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 5
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_10
    on_release:
      then:
        - light.toggle: light_10
        
### Tecla switch relay 20 ###
  - platform: gpio
    name: sw20-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 4
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_13
    on_release:
      then:
        - light.toggle: light_13
        
### Tecla switch relay 21 ###
  - platform: gpio
    name: sw21-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 3
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_10
    on_release:
      then:
        - light.toggle: light_10
        
### Tecla switch relay 22 ###
  - platform: gpio
    name: sw22-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 2
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_10
    on_release:
      then:
        - light.toggle: light_10
        
### Tecla switch relay 23 ###
  - platform: gpio
    name: sw23-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 1
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_10
    on_release:
      then:
        - light.toggle: light_10
        
### Tecla switch relay 24 ###
  - platform: gpio
    name: sw24-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 0
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_10
    on_release:
      then:
        - light.toggle: light_10
        
### Tecla switch relay 25 ###
  - platform: gpio
    name: sw25-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 15
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_10
    on_release:
      then:
        - light.toggle: light_10
        
### Tecla switch relay 26 ###
  - platform: gpio
    name: sw26-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 14
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_10
    on_release:
      then:
        - light.toggle: light_10
        
### Tecla switch relay 27 ###
  - platform: gpio
    name: sw27-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 13
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_10
    on_release:
      then:
        - light.toggle: light_10
        
### Tecla switch relay 28 ###
  - platform: gpio
    name: sw28-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 12
      mode:
        input: true
        pullup: true
      inverted: false
#    on_press:
#      then:
#        - light.toggle: light_10
#    on_release:
#      then:
#        - light.toggle: light_10
        
### Tecla switch relay 29 ###
  - platform: gpio
    name: sw29-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 11
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_15
    on_release:
      then:
        - light.toggle: light_15
        
### Tecla switch relay 30 ###
  - platform: gpio
    name: sw30-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 10
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_10
    on_release:
      then:
        - light.toggle: light_10
        
### Tecla switch relay 31 ###
  - platform: gpio
    name: sw31-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 9
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_14
    on_release:
      then:
        - light.toggle: light_14
        
### Tecla switch relay 32 ###
  - platform: gpio
    name: sw32-p1
    filters:
      - delayed_on_off: $delay
    pin:
      mcp23xxx: hub_switch2
      number: 8
      mode:
        input: true
        pullup: true
      inverted: false
    on_press:
      then:
        - light.toggle: light_15
    on_release:
      then:
        - light.toggle: light_15